corkboard/routes.py
import os
import secrets
from PIL import Image
from flask import render_template, url_for, flash, redirect, request,  send_from_directory,  abort, current_app, jsonify, Blueprint
from corkboard import db, bcrypt, mail
from corkboard.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm, PostForm
from corkboard.models import User, Board, Comment, Starred
from flask_login import login_user, current_user, logout_user, login_required
from flask_mail import Message
from werkzeug.utils import secure_filename

main = Blueprint('main', __name__)



@main.route("/")
def index():
    template_name = 'landingPage.html'
    return render_template('landingPage.html',template_name=template_name)

@main.route("/")
@main.route("/home")
def home():
    template_name = 'home.html'
    page = request.args.get('page', 1, type=int)
    posts = Board.query.order_by(Board.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts, template_name=template_name)

@main.route('/home/favoriteboards')
@login_required  # Require authentication to access this route
def favoriteboards():
    template_name='starredBoards.html'
    # Fetch the liked posts by the current user from the Starred model
    liked_posts = Board.query.join(Starred, (Starred.post_id == Board.id)).filter(
        Starred.author == current_user.id).order_by(Board.date_posted.desc()).all()

    return render_template('starredBoards.html', liked_posts=liked_posts, template_name='starredBoards.html')

@main.route("/home/landingPage")
def landingPage():
    template_name = 'landingPage.html'
    return render_template('landingPage.html', template_name=template_name)

@main.route("/about")
def about():
    return render_template('about.html', title='About')


@main.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('main.login'))
    return render_template('register.html', title='Register', form=form)


@main.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@main.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.landingPage'))

@main.route("/contactus")
def contactus():
    return render_template('contactus.html')


def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(current_app.root_path, 'static/profile_pics', picture_fn)

    output_size = (125, 125)
    i = Image.open(form_picture)
    i.thumbnail(output_size)
    i.save(picture_path)

    return picture_fn




@main.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('main.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)




def send_reset_email(user):
    token = user.get_reset_token()
    msg = Message('Password Reset Request',
                  sender='noreply@demo.com',
                  recipients=[user.email])
    msg.body = f'''To reset your password, visit the following link:
{url_for('main.reset_token', token=token, _external=True)}
If you did not make this request then simply ignore this email and no changes will be made.
'''
    mail.send(msg)


@main.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('main.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@main.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('main.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('main.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)










ALLOWED_EXTENSIONS = {'txt', 'pdf', 'doc', 'docx', 'png'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

def save_file1(file):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(file.filename)
    file_fn = random_hex + f_ext

    # Ensure the 'static/uploads' directory exists
    upload_folder = os.path.join(current_app.root_path, 'static', 'uploads')
    os.makedirs(upload_folder, exist_ok=True)

    file_path = os.path.join(upload_folder, file_fn)

    file.save(file_path)

    return file_fn

@main.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        content = form.content.data
        file = form.file.data

        if file and allowed_file(file.filename):
            file_path = save_file1(file)
        else:
            file_path = None  # Handle the case where no valid file is provided

        board = Board(title=title, content=content, author=current_user, file_path=file_path)
        db.session.add(board)
        db.session.commit()

        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))

    return render_template('create_post.html', title='New Post', form=form, legend='New Post')

@main.route('/static/uploads/<path:filename>')
def serve_static(filename):
    upload_folder = current_app.config['UPLOAD_FOLDER']
    return send_from_directory( upload_folder, filename)
    
@main.route("/post/<int:post_id>")
def post(post_id):
    post = Board.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)




@main.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Board.query.get_or_404(post_id)

    # Ensure only the author can update the post
    if post.author != current_user:
        abort(403)

    form = PostForm()

    if form.validate_on_submit():
        # Handle file upload if necessary
        file = form.file.data
        if file:
            # Save the file using the save_file1 function
            file_path = save_file1(file)
            
            # Update post file path
            post.file_path = file_path

        # Update post data
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()

        flash('Your post has been updated!', 'success')
        return redirect(url_for('main.post', post_id=post.id))

    # Pre-populate form fields after validating form submission
    form.title.data = post.title
    form.content.data = post.content

    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')



@main.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Board.query.get_or_404(post_id)

    # Check if the current user is the author of the post
    if post.author != current_user:
        abort(403)

    try:
        # Delete all associated comments first
        Comment.query.filter_by(post_id=post.id).delete()
        Starred.query.filter_by(post_id=post.id).delete()

        # Delete the post
        db.session.delete(post)
        db.session.commit()

        flash('Your post and associated comments have been deleted!', 'success')
    except Exception as e:
        # Handle exceptions if necessary
        flash(f'Error deleting post: {str(e)}', 'error')

corkboard/templates/about.html
{% extends "layout.html" %}
{% block content %}

    <div class="content-section">
        <h1 style="text-align: center;">About Page</h1>
        <h3>Our Story</h3>
        <p>CorkBoard  is about giving people the power to create space to find belonging in their lives.
         We want to make it easier for you to talk regularly with the people you care about. We want you 
        to build genuine relationships with your friends and communities close to home or around the world.</p>

        <div class="card mt-4">
            <h3 class="card-header">Why It Works</h3>
            <div class="card-body">
                <h5 class="card-title">Personalized Content</h5>
                <p class="card-text">Website that creates a collaborative environment where people can view and add things to a digital CorkBoard</p>
                <h5 class="card-title">Trusted Content</h5>
                <p class="card-text"></p>Created by experts in their field of expertise.</p>
                <h5 class="card-title">Tools to empower</h5>
                <p class="card-text"></p>CorkBoard allows people to search, add, and create boards.</p>
            </div>
        </div>
    </div>

{% endblock content %}

corkboard/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

corkboard/templates/contactus.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Contact Us</legend>
                <div class="form-group">
                    <label for="firstName">First Name</label>
                    <input type="text" class="form-control" id="firstName">
                </div>
                <div class="form-group">
                    <label for="lasttName">Last Name</label>
                    <input type="text" class="form-control" id="lastName">
                </div>
                <div class="form-group">
                    <label for="email">Email Address</label>
                    <input type="email" class="form-control" id="email">
                </div>
                <div class="form-group">
                    <label for="message">Message</label>
                    <textarea class="form-control" id="message" rows="4"></textarea>
                </div>
                <button type="submit" class="btn btn-outline-info">Submit</button>
            </fieldset>
        </form>
    </div>
{% endblock content %}

corkboard/templates/home.html
{% extends "layout.html" %}
{% block content %}
  <div style="margin-left: 94%;">
    <div class="mb-3">
      <a class="btn btn-outline-info mb-4" href="{{ url_for('main.new_post') }}" role="button">
        <div style="size: 50px;">  
        +
        </div>
      </a>
    </div>
  </div>
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body" >
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('main.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
              <div class="d-flex justify-content-end align-items-center">
                <div class="mr-2">{{ post.likes|length }}</div>
                
                <div>
                    {% if current_user.id in post.likes|map(attribute="author")|list %}
                        <a href="{{ url_for('main.like_post', post_id=post.id) }}"><i class="fas fa-star"></i></a>
                    {% else %}
                        <a href="{{ url_for('main.like_post', post_id=post.id) }}"><i class="far fa-star"></i></a>
                    {% endif %}
                </div>
            </div>
            </div>
            <h2><a class="article-title" href="{{ url_for('main.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
            {% if post.file_path %}
              {% if post.file_path|file_type == 'image' %}
                <img src="{{ url_for('static', filename='uploads/' + post.file_path) }}" class="card-img-top" alt="File Preview">
              {% elif post.file_path|file_type == 'video' %}
                <video width="320" height="240" controls>
                  <source src="{{ url_for('static', filename='uploads/' + post.file_path) }}" type="video/mp4">
                  Your browser does not support the video tag.
                </video>
              {% else %}
              <p>File: <a href="{{ url_for('static', filename='uploads/' + post.file_path) }}" target="_blank" download>Download File</a> </p>
              {% endif %}
            {% endif %}
          </div>
        </article>
        


    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

corkboard/templates/landingPage.html
{% extends "layout.html" %}
{% block content %}

<div style="margin-left: 40%;">
    <h1>Welcome to Cork Board</h1>
</div>

<div style="margin-top: 1cm;">
    <div class="Landing-content" style="text-align:left"> 
        <p> 
            Discover, join, and stay updated with activities and 
            announcements across campus. Cork Board enables 
            students to highlight club and campus events in a fun and organized way. 
        </p>
    </div>
</div>



<div style="margin-left: 20%; margin-top: 30px;">
    <h3>Why Choose Cork Board</h3>
</div>

<div style="margin-top: 5px;">
    <div class="Landing-content" style="text-align:left"> 
        <p> 
            Cork Board allows you to organize and design your personal space. 
            This allows for ease of use and access when it comes to planning your next events. 
            Cork Board is great for organizations with constantly moving events with times and locations. 
            With Cork Board, you have an open space in which people can communicate
        </p>
    </div>
</div>


{% endblock content %}

corkboard/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha384-xxx" crossorigin="anonymous">


    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>CorkBoard- {{ title }}</title>
    {% else %}
        <title>CorkBoard</title>
    {% endif %}
  
</head>
<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #925B33;">
      <div class="container">
        <a class="navbar-brand mr-4" href="/">CorkBoard</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarToggle">
          {% if current_user.is_authenticated %}
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="{{ url_for('main.new_post') }}">New Post</a>
              <a class="nav-item nav-link" href="{{ url_for('main.account') }}">Account</a>
              <a class="nav-item nav-link" href="{{ url_for('main.logout') }}">Logout</a>
            </div>
          {% else %}
            <!-- Navbar Right Side for Non-authenticated users -->
            <div class="navbar-nav ml-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.login') }}">Login</a>
              <a class="nav-item nav-link" href="{{ url_for('main.register') }}">Register</a>
            </div>
          {% endif %}
        </div>
      </div>
    </nav>
  </header>
  
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>

        {% if template_name in ['home.html', 'starredBoards.html', 'search_user.html', 'user_posts.html'] %}
            <div class="col-md-4">
              <div class="content-section">
                
                <h3>Menu</h3>
                <p class='text-muted'>You can put any information here you'd like.
                  <ul class="list-group">
                
                    <li class="list-group-item list-group-item-light">
                      <a class="article-title" href="{{ url_for('main.favoriteboards') }}">Starred Boards </a>
                    </li>

                    <li class="list-group-item list-group-item-light">
                      <a class="article-title" href="{{ url_for('main.search_user') }}">Search Boards </a>
                    </li>

                  </ul>
                </p>
                

              </div>
            </div> 
        {% endif %}
  
      </div>
    </main>
   
    
    <footer class="mt-3 fixed-bottom">
      <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #925B33;">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">CorkBoard</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
              <a class="nav-item nav-link" href="{{ url_for('main.contactus') }}">Contact Us</a>
            </div>
            
          </div>
        </div>
          
      </nav>
  </footer>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/a14e6235fb.js" crossorigin="anonymous"></script>

</body>

</html>

corkboard/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <a href="{{ url_for('main.reset_request') }}">Forgot Password?</a>
            </div>
           
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('main.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

corkboard/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('main.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        <div class="d-flex justify-content-end align-items-center">
          <div class="mr-2">{{ post.likes|length }}</div>
          
          <div>
              {% if current_user.id in post.likes|map(attribute="author")|list %}
                  <a href="{{ url_for('main.like_post', post_id=post.id) }}"><i class="fas fa-star"></i></a>
              {% else %}
                  <a href="{{ url_for('main.like_post', post_id=post.id) }}"><i class="far fa-star"></i></a>
              {% endif %}
          </div>
      </div>
      
       

       
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('main.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>

      {% if post.file_path %}
        <p>File: <a href="{{ url_for('static', filename='uploads/' + post.file_path) }}" target="_blank">{{ post.file_path }}</a></p>
      {% endif %}

    
    
      <div class="collapse" id="comments-{{post.id}}">
        <div class="card">
          <div class="card-body" id="comments-expanded-{{post.id}}">
            {% for comment in post.comments %}
            <div class="d-flex justify-content-between align-items-center">
              <div>
                <a href="{{ url_for('main.user_posts', username=comment.author.username) }}">
                  {{comment.author.username}}</a
                >: {{comment.text}}
              </div>
              <div>
                <small class="text-muted"> {{comment.date_created}}</small>
                {% if current_user.id == comment.author_id or current_user== post.author %}
                <div class="btn-group">
                  <button
                    type="button"
                    class="btn btn-sm btn-primary dropdown-toggle"
                    data-toggle="dropdown"
                  ></button>
                  <ul class="dropdown-menu">
                    <li>
                      <a
                        href="/delete_comment/{{comment.id}}"
                        class="dropdown-item"
                        >Delete</a
                      >
                    </li>
                  </ul>
                </div>
                {% endif %}
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
          <p class="card-text">
            {% if post.comments|length > 0 %}
                <a data-toggle="collapse" href="#comments-{{post.id}}" role="button">
                    <small>View {{post.comments|length}} Comments</small>
                </a>
            {% else %}
                <small class="text-muted">No Comments</small>
            {% endif %}
        </p>
          <form class="input-group mb-3" method="POST" action="/create_comment/{{post.id}}" style="align-items: baseline;">
            <input type="text" id="text" name="text" class="form-control" placeholder="Comment something!">
            <div class="input-group-append">
                <button type="submit" class="btn btn-outline-info mb-4" style="margin-top: 0;">Comment</button>
            </div>
        </form>  
  
    </div>

    
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('main.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}